
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "./Navbar";
import StoreProvider from "../ReduxReducers/provider";
import FluidCursor from '../components/FliudCursor';
import Wrapper from "./Wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

    <FluidCursor/>
        <StoreProvider >
        <Wrapper>
        <Navbar />
        <main className="pt-20 bg-[#eaf2fb] min-h-screen">
          {children}
        </main>
        </Wrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
