
import AttendeeSidebar from './components/attendee/AttendeeSidebar';
import OrganizerSidebar from './components/organizer/OrganizerSidebar';
import '../globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import StoreProvider from "../ReduxReducers/provider";
import Navbar from './components/Navbar';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'EventFlow — Manage Events with Ease',
  description: 'Generated by Create Next App',
};

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <StoreProvider>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* Grid Layout */}
        <div className="grid grid-cols-[224px_1fr] h-[100vh] overflow-hidden p-4 bg-[#F8FAFC] gap-2 rounded-2xl">
          {/* Sidebar - Fixed height, no scroll */}
          <div className="h-full md:block">
           <Navbar/>
          </div>
          {/* Main Content - Scrolls vertically if needed */}
          <main className="h-full overflow-y-auto bg-[#F8FAFC] p-0 rounded-3xl scroll-hide">
            {children}
          </main>
        </div>
      </body>
      </StoreProvider>
    </html>
  );
}
